(rule
 (target byterun.exe)
 (deps
  (:include (source_tree include))
  (:main src/cli.c src/interpreter.c)
  (:parser src/parser.c)
  (:utils src/utils.c src/types.c src/stack.c)
  (:runtime ../runtime/runtime.a))
 (mode
  (promote (until-clean)))
 (action
  (run gcc -Iinclude/ -g %{main} %{parser} %{utils} %{runtime} -o %{target})))
